<?php


namespace Pressmind\System;


class Info
{
    const STATIC_MODELS = [
        '\Airline',
        '\Airport',
        '\Bank',
        '\Brand',
        '\ObjectdataTag',
        '\Geozip',
        '\CategoryTree',
        '\CategoryTree\Item',
        '\CheapestPriceSpeed',
        '\DataView',
        '\DataView\SearchCondition',
        '\FulltextSearch',
        '\Scheduler\Task',
        '\Scheduler\Task\Method',
        '\MediaObject',
        '\MediaObject\DataType\Categorytree',
        '\MediaObject\DataType\File',
        '\MediaObject\DataType\Link',
        '\MediaObject\DataType\Location',
        '\MediaObject\DataType\Objectlink',
        '\MediaObject\DataType\Picture',
        '\MediaObject\DataType\Picture\Section',
        '\MediaObject\DataType\Picture\Derivative',
        '\MediaObject\DataType\Table',
        '\MediaObject\DataType\Table\Row',
        '\MediaObject\DataType\Table\Row\Column',
        '\MediaObject\DataType\Key_value',
        '\MediaObject\DataType\Key_value\Row',
        '\MediaObject\DataType\Key_value\Row\Column',
        '\MediaObject\MyContent',
        '\Route',
        '\Search',
        '\Season',
        '\Touristic\Base',
        '\Touristic\Booking\Earlybird',
        '\Touristic\Booking\Package',
        '\Touristic\Date',
        '\Touristic\ExtrasToMediaObject',
        '\Touristic\Housing\Package',
        '\Touristic\Housing\Package\DescriptionLink',
        '\Touristic\Insurance',
        '\Touristic\Insurance\Group',
        '\Touristic\Insurance\InsuranceToGroup',
        '\Touristic\Insurance\PriceTable',
        '\Touristic\Option',
        '\Touristic\Option\Description',
        '\Touristic\Pickupservice',
        '\Touristic\Pickupservice\Option',
        '\Touristic\SeasonalPeriod',
        '\Touristic\Startingpoint',
        '\Touristic\Startingpoint\Option',
        '\Touristic\Startingpoint\Option\ZipRange',
        '\Touristic\Transport',
        '\Itinerary\Variant',
        '\Itinerary\Variant\Step',
        '\Itinerary\Variant\Step\Geopoint',
        '\Itinerary\Variant\Step\DocumentMediaObject',
        '\Itinerary\Variant\Step\DocumentMediaObject\Derivative',
        '\Itinerary\Variant\Step\Board',
        '\Itinerary\Variant\Step\Section',
        '\Itinerary\Variant\Step\Section\Content'
    ];
}
