<?php


namespace Pressmind\ORM\Object\Touristic\Insurance;


use Pressmind\DB\Adapter\Pdo;
use Pressmind\ORM\Object\AbstractObject;
use Pressmind\Registry;

/**
 * Class InsuranceToAttribute
 * @package Pressmind\ORM\Object\Touristic\Insurance
 * @property string $id_insurance
 * @property string $id_attribute
 */
class InsuranceToAttribute extends AbstractObject
{
    protected $_dont_use_autoincrement_on_primary_key = true;

    protected $_replace_into_on_create = true;

    protected $_definitions = array(
        'class' => [
            'name' => self::class,
        ],
        'database' => [
            'table_name' => 'pmt2core_touristic_insurance_to_attributes',
            'primary_key' => [
                'id_insurance',
                'id_attribute'
            ],
        ],
        'properties' =>
            [
                'id_insurance' => [
                    'title' => 'id_insurance',
                    'name' => 'id_insurance',
                    'type' => 'string',
                    'required' => true,
                    'validators' => [
                        [
                            'name' => 'maxlength',
                            'params' => 32,
                        ],
                    ],
                    'filters' => NULL,
                    'index' => [
                        'id_insurance' => 'index'
                    ]
                ],
                'id_attribute' => [
                    'title' => 'id_attribute',
                    'name' => 'id_attribute',
                    'type' => 'string',
                    'required' => true,
                    'validators' => [
                       [
                           'name' => 'maxlength',
                           'params' => 32,
                       ],
                    ],
                    'filters' => NULL,
                    'index' => [
                        'id_attribute' => 'index'
                    ]
                ]
            ]
    );

    public function delete($deleteRelations = false)
    {
        /** @var Pdo $db */
        $db = Registry::getInstance()->get('db');
        $db->execute('DELETE FROM ' . $this->getDbTableName() . ' WHERE id_attribute = ? AND id_insurance = ?', [$this->id_attribute, $this->id_insurance]);
        //parent::delete($deleteRelations); // TODO: Change the autogenerated stub
    }
}
